# Generated by Django 3.0.2 on 2020-01-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan',
            fields=[
                ('s_date', models.DateField(verbose_name='Start Date')),
                ('e_date', models.DateField(verbose_name='End Date')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('places', models.CharField(max_length=5000)),
            ],
        ),
    ]
