# Generated by Django 3.0.2 on 2020-01-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20200125_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Plan'),
        ),
    ]
